# Generated by Django 4.0.5 on 2022-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('external_id', models.IntegerField(null=True, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
            ],
        ),
    ]
